Output directory is:  ../../attributes
Input file is:  ../../Nii_files

File "/usr/local/machine-learning/anaconda/envs/nibabel/lib/python3.7/site-packages/nibabel/volumeutils.py", line 539, in array_from_file
    getattr(infile, 'name', 'object')))
OSError: Expected 39321600 bytes, got 7863968 bytes from ../../Nii_files/ADNI1_Complete_1Yr_3T/ADNI/016_S_0769/MPR__GradWarp__B1_Correction__N3__Scaled/2007-03-21_14_17_54.0/S28899/ADNI_016_S_0769_MR_MPR__GradWarp__B1_Correction__N3__Scaled_Br_20071229173837136_S28899_I86309.nii
 - could the file be damaged?
"""

